spring:
  application:
    name: musinsa-coding-assignment
  datasource:
    url: jdbc:h2:mem:musinsa
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.H2Dialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true
  mvc:
    problemdetails:
      enabled: true
springdoc:
  packages-to-scan: com.musinsa.musinsacodingassignment
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  swagger-ui:
    path: /swagger-ui
    disable-swagger-default-url: true
    display-request-duration: true
    operations-sorter: alpha
